# Generated by Django 2.1.2 on 2018-10-14 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_auto_20181013_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.BigIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99999999999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
